apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerhub-sample-app
  labels:
    app: dockerhub-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerhub-sample-app
  template:
    metadata:
      labels:
        app: dockerhub-sample-app
    spec:
      containers:
        - name: sample-app
          image: techsubrat07/myapp:latest
          ports:
            - containerPort: 80
