apiVersion: v1
kind: Service
metadata:
  name: dockerhub-sample-service
spec:
  type: NodePort
  selector:
    app: dockerhub-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007   # You can choose any port between 30000â€“32767

